#import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 0.6
blur = true
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
size = 19.0

[keyboard]
bindings = [
  { key = "Backspace", mods = "Command", chars = "\u0015" },
  { key = "Left", mods = "Command", chars = "\u0001" },
  { key = "Right", mods = "Command", chars = "\u0005" },
]

[colors]
cursor = { text = "#000000", cursor = "#74E291" }

[colors.primary]
background = "#000000"
